{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{ toYaml .Values.ingress.rules | indent 4}}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.nexusProxy.env.nexusDockerHost }}
      - {{ .Values.nexusProxy.env.nexusHttpHost }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
{{- end -}}
{{- end }}
