{{- if eq .Values.postgresql.enabled false -}}
{{- if not .Values.postgresql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end -}}
{{- end -}}
