apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
  labels:
    app: nexus-deployment
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard