{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nexus.serviceAccountName" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
{{- end -}}
