apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: nexus
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: repo 
  selector:
    app.kubernetes.io/name: {{ include "nexus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
